name: Knowledge Graph E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package.json
      
      - name: Install dependencies
        run: |
          npm ci || npm install
          npm install -g http-server
      
      - name: List files for debugging
        run: |
          ls -la
          ls -la js/
          ls -la js/modules/
      
      - name: Start web server in background
        run: |
          http-server -p 8000 --cors -c-1 &
          echo $! > ./server.pid
          sleep 15  # Give the server more time to start
          curl -v http://localhost:8000/ || echo "Server not responding"
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          config: '{"defaultCommandTimeout":10000,"responseTimeout":30000,"requestTimeout":30000}'
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
      
      - name: Stop web server
        if: always()
        run: |
          if [ -f ./server.pid ]; then
            kill $(cat ./server.pid) || true
          fi
