name: Knowledge Graph E2E Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'knowledge-graph/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'knowledge-graph/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: knowledge-graph
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: knowledge-graph/package.json
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Start web server in background
        run: |
          npm install -g http-server
          http-server -p 8000 &
          sleep 5  # Give the server time to start
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: knowledge-graph
          browser: chrome
          headed: false
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 30
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: knowledge-graph/cypress/screenshots
          if-no-files-found: ignore
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: knowledge-graph/cypress/videos
          if-no-files-found: ignore
